// Comprehensive mock data — replaced with real API calls once keys are configured

export const MARKET_INDICES = [
  { name: "S&P 500", ticker: "SPX", value: 5487.23, change: 18.42, pct: 0.34 },
  { name: "NASDAQ", ticker: "COMP", value: 17857.02, change: -24.18, pct: -0.14 },
  { name: "DOW", ticker: "DJI", value: 40003.59, change: 156.73, pct: 0.39 },
  { name: "Russell 2000", ticker: "RUT", value: 2043.11, change: -8.44, pct: -0.41 },
  { name: "VIX", ticker: "VIX", value: 14.82, change: -0.63, pct: -4.08 },
  { name: "10-Yr Treasury", ticker: "TNX", value: 4.28, change: 0.03, pct: 0.71 },
];

export const SECTOR_PERFORMANCE = [
  { name: "Technology", pct: 1.42, color: "#3b82f6" },
  { name: "Healthcare", pct: 0.87, color: "#10b981" },
  { name: "Financials", pct: 0.63, color: "#10b981" },
  { name: "Energy", pct: -0.21, color: "#ef4444" },
  { name: "Consumer Disc.", pct: 0.38, color: "#10b981" },
  { name: "Industrials", pct: 0.52, color: "#10b981" },
  { name: "Comm. Services", pct: 1.18, color: "#3b82f6" },
  { name: "Utilities", pct: -0.34, color: "#ef4444" },
  { name: "Materials", pct: 0.14, color: "#64748b" },
  { name: "Real Estate", pct: -0.58, color: "#ef4444" },
  { name: "Cons. Staples", pct: 0.22, color: "#10b981" },
];

export const MACRO_INDICATORS = [
  { label: "Fed Funds Rate", value: "5.25–5.50%", trend: "flat", note: "No cut expected before Sept 2025" },
  { label: "CPI (YoY)", value: "3.2%", trend: "down", note: "Moderating but above 2% target" },
  { label: "Core PCE", value: "2.8%", trend: "down", note: "Fed's preferred inflation gauge" },
  { label: "GDP Growth (Q1)", value: "+2.1%", trend: "up", note: "Above consensus estimates" },
  { label: "Unemployment", value: "3.9%", trend: "up", note: "Labor market softening slightly" },
  { label: "10Y–2Y Spread", value: "-0.42%", trend: "up", note: "Inversion narrowing" },
  { label: "WTI Crude", value: "$79.40", trend: "down", note: "Demand concerns weighing" },
  { label: "DXY (USD)", value: "104.2", trend: "flat", note: "Holding above 104 support" },
];

export const EARNINGS_CALENDAR = [
  { date: "Jun 24", ticker: "NVDA", name: "NVIDIA", est: "$0.65", type: "after" },
  { date: "Jun 25", ticker: "MU", name: "Micron", est: "$0.51", type: "after" },
  { date: "Jun 26", ticker: "PAYX", name: "Paychex", est: "$1.18", type: "before" },
  { date: "Jul 9", ticker: "DAL", name: "Delta Air Lines", est: "$2.30", type: "before" },
  { date: "Jul 11", ticker: "JPM", name: "JPMorgan Chase", est: "$4.19", type: "before" },
  { date: "Jul 12", ticker: "C", name: "Citigroup", est: "$1.56", type: "before" },
  { date: "Jul 15", ticker: "GS", name: "Goldman Sachs", est: "$8.73", type: "before" },
  { date: "Jul 16", ticker: "NFLX", name: "Netflix", est: "$4.69", type: "after" },
  { date: "Jul 22", ticker: "TSLA", name: "Tesla", est: "$0.62", type: "after" },
  { date: "Jul 23", ticker: "GOOGL", name: "Alphabet", est: "$1.84", type: "after" },
  { date: "Jul 24", ticker: "META", name: "Meta Platforms", est: "$4.71", type: "after" },
  { date: "Jul 30", ticker: "MSFT", name: "Microsoft", est: "$3.09", type: "after" },
];

export const ANALYST_ACTIONS = [
  { ticker: "NVDA", analyst: "Morgan Stanley", action: "Upgrade", from: "Equal Weight", to: "Overweight", pt: 1200 },
  { ticker: "META", analyst: "Goldman Sachs", action: "Initiate", from: null, to: "Buy", pt: 580 },
  { ticker: "AMZN", analyst: "JPMorgan", action: "Reiterate", from: "Overweight", to: "Overweight", pt: 230 },
  { ticker: "INTC", analyst: "Barclays", action: "Downgrade", from: "Overweight", to: "Equal Weight", pt: 32 },
  { ticker: "AAPL", analyst: "UBS", action: "Reiterate", from: "Buy", to: "Buy", pt: 235 },
  { ticker: "TSLA", analyst: "Wells Fargo", action: "Downgrade", from: "Equal Weight", to: "Underweight", pt: 120 },
];

export const COMPANY_UNIVERSE = [
  {
    ticker: "AAPL",
    name: "Apple Inc.",
    sector: "Technology",
    industry: "Consumer Electronics",
    marketCap: 3150000, // $M
    price: 213.07,
    change: 0.84,
    pct: 0.40,
    pe: 33.2,
    evEbitda: 24.8,
    revenue: 385600, // TTM $M
    revenueGrowth: 2.9,
    grossMargin: 46.2,
    ebitdaMargin: 33.4,
    netMargin: 25.3,
    fcfMargin: 27.1,
    roe: 160.6,
    debtToEbitda: 1.2,
    analystRating: "Overweight",
    avgPt: 235,
    opportunityScore: 72,
    dcfUpside: 10.3,
    shariah: "Compliant",
    description: "Apple designs, manufactures, and markets consumer electronics, computer software, and online services. Its ecosystem of iPhone, Mac, iPad, Wearables, and Services creates powerful switching costs and recurring revenue.",
    moat: "Ecosystem lock-in, brand premium, App Store distribution monopoly",
    risks: ["Smartphone market saturation", "China revenue concentration (~19%)", "Regulatory pressure on App Store"],
    revenueHistory: [274515, 365817, 394328, 383285, 385600],
    ebitdaHistory: [77344, 119437, 130541, 119052, 128780],
    fcfHistory: [73365, 92953, 111443, 99584, 104476],
    years: [2020, 2021, 2022, 2023, 2024],
    revenueForcast: [392000, 408000, 425000, 443000, 462000],
    impliedPrice: 235.0,
    wacc: 9.1,
    tgr: 3.0,
    exitMultiple: 22,
    bullPrice: 285,
    baseprice: 235,
    bearPrice: 165,
  },
  {
    ticker: "MSFT",
    name: "Microsoft Corporation",
    sector: "Technology",
    industry: "Software—Infrastructure",
    marketCap: 3280000,
    price: 441.16,
    change: 2.33,
    pct: 0.53,
    pe: 37.8,
    evEbitda: 27.2,
    revenue: 245122,
    revenueGrowth: 17.6,
    grossMargin: 69.4,
    ebitdaMargin: 52.6,
    netMargin: 35.6,
    fcfMargin: 34.2,
    roe: 38.7,
    debtToEbitda: 0.6,
    analystRating: "Overweight",
    avgPt: 490,
    opportunityScore: 84,
    dcfUpside: 11.1,
    shariah: "Compliant",
    description: "Microsoft develops and licenses software, cloud services, and devices. Azure is the fastest-growing hyperscaler, Copilot is monetizing AI across its 365/Teams suite, and the OpenAI partnership positions it uniquely in the AI era.",
    moat: "Enterprise switching costs, Azure ecosystem, Office 365 integration",
    risks: ["Azure growth deceleration", "Copilot monetization uncertainty", "Antitrust scrutiny from Activision deal"],
    revenueHistory: [143015, 168088, 198270, 211915, 245122],
    ebitdaHistory: [65688, 83383, 97982, 104408, 128913],
    fcfHistory: [45199, 56118, 65149, 72322, 83826],
    years: [2020, 2021, 2022, 2023, 2024],
    revenueForcast: [282000, 320000, 363000, 410000, 458000],
    impliedPrice: 490,
    wacc: 8.8,
    tgr: 3.5,
    exitMultiple: 25,
    bullPrice: 580,
    baseprice: 490,
    bearPrice: 350,
  },
  {
    ticker: "NVDA",
    name: "NVIDIA Corporation",
    sector: "Technology",
    industry: "Semiconductors",
    marketCap: 2980000,
    price: 120.44,
    change: 3.21,
    pct: 2.74,
    pe: 55.6,
    evEbitda: 48.2,
    revenue: 79775,
    revenueGrowth: 122.4,
    grossMargin: 74.6,
    ebitdaMargin: 61.7,
    netMargin: 55.0,
    fcfMargin: 50.4,
    roe: 123.6,
    debtToEbitda: 0.4,
    analystRating: "Overweight",
    avgPt: 150,
    opportunityScore: 91,
    dcfUpside: 24.5,
    shariah: "Compliant",
    description: "NVIDIA designs GPUs for AI training, data center inference, gaming, and professional visualization. The Hopper architecture and upcoming Blackwell platform make NVDA the critical picks-and-shovels play of the AI infrastructure buildout.",
    moat: "CUDA ecosystem moat, proprietary architecture, customer stickiness (hyperscalers)",
    risks: ["Export controls on China", "Valuation requires sustained hypergrowth", "AMD/Intel competition", "Custom silicon from hyperscalers"],
    revenueHistory: [10918, 16675, 26914, 44870, 79775],
    ebitdaHistory: [4035, 6426, 11007, 22101, 49220],
    fcfHistory: [4694, 6001, 9044, 26948, 40220],
    years: [2020, 2021, 2022, 2023, 2024],
    revenueForcast: [125000, 170000, 210000, 250000, 290000],
    impliedPrice: 150,
    wacc: 10.2,
    tgr: 4.0,
    exitMultiple: 40,
    bullPrice: 200,
    baseprice: 150,
    bearPrice: 90,
  },
  {
    ticker: "AMZN",
    name: "Amazon.com Inc.",
    sector: "Consumer Discretionary",
    industry: "Internet Retail",
    marketCap: 1980000,
    price: 189.30,
    change: 0.92,
    pct: 0.49,
    pe: 48.2,
    evEbitda: 21.4,
    revenue: 590740,
    revenueGrowth: 12.5,
    grossMargin: 48.0,
    ebitdaMargin: 17.8,
    netMargin: 5.8,
    fcfMargin: 12.4,
    roe: 23.4,
    debtToEbitda: 1.1,
    analystRating: "Overweight",
    avgPt: 230,
    opportunityScore: 82,
    dcfUpside: 21.5,
    shariah: "Questionable",
    description: "Amazon operates e-commerce, AWS (the world's largest cloud), advertising, and Prime ecosystem. AWS and advertising are high-margin businesses masking low retail margins but generating enormous free cash flow.",
    moat: "AWS ecosystem, Prime loyalty, logistics network, advertising data",
    risks: ["AWS growth competition from Azure/GCP", "Antitrust scrutiny", "Retail margin pressure"],
    revenueHistory: [380939, 469822, 513983, 554028, 590740],
    ebitdaHistory: [35829, 55528, 41844, 85451, 105050],
    fcfHistory: [21325, 25921, -11569, 32826, 73267],
    years: [2020, 2021, 2022, 2023, 2024],
    revenueForcast: [648000, 720000, 800000, 885000, 975000],
    impliedPrice: 230,
    wacc: 9.5,
    tgr: 3.2,
    exitMultiple: 18,
    bullPrice: 275,
    baseprice: 230,
    bearPrice: 160,
  },
  {
    ticker: "GOOGL",
    name: "Alphabet Inc.",
    sector: "Communication Services",
    industry: "Internet Content",
    marketCap: 2210000,
    price: 178.02,
    change: 1.56,
    pct: 0.88,
    pe: 26.4,
    evEbitda: 18.2,
    revenue: 307394,
    revenueGrowth: 14.4,
    grossMargin: 56.9,
    ebitdaMargin: 32.5,
    netMargin: 24.0,
    fcfMargin: 21.8,
    roe: 29.0,
    debtToEbitda: 0.1,
    analystRating: "Overweight",
    avgPt: 210,
    opportunityScore: 86,
    dcfUpside: 17.9,
    shariah: "Compliant",
    description: "Alphabet's Google dominates search (92% market share) and YouTube, while GCP is the #3 cloud and Waymo is the leading autonomous vehicle platform. Trading at a discount to peers despite best-in-class AI positioning with Gemini.",
    moat: "Search monopoly, data advantage, YouTube dominance, Android ecosystem",
    risks: ["AI threatens search revenue model", "DOJ antitrust ruling", "Ad market cyclicality"],
    revenueHistory: [182527, 257637, 282836, 307394, 307394],
    ebitdaHistory: [47258, 76660, 79591, 91929, 99954],
    fcfHistory: [42843, 67012, 60010, 69495, 67014],
    years: [2020, 2021, 2022, 2023, 2024],
    revenueForcast: [345000, 390000, 440000, 495000, 553000],
    impliedPrice: 210,
    wacc: 9.0,
    tgr: 3.5,
    exitMultiple: 17,
    bullPrice: 255,
    baseprice: 210,
    bearPrice: 145,
  },
  {
    ticker: "META",
    name: "Meta Platforms Inc.",
    sector: "Communication Services",
    industry: "Internet Content",
    marketCap: 1260000,
    price: 499.42,
    change: 5.11,
    pct: 1.03,
    pe: 27.2,
    evEbitda: 18.8,
    revenue: 134902,
    revenueGrowth: 22.1,
    grossMargin: 81.7,
    ebitdaMargin: 43.2,
    netMargin: 35.3,
    fcfMargin: 30.4,
    roe: 33.7,
    debtToEbitda: 0.0,
    analystRating: "Overweight",
    avgPt: 575,
    opportunityScore: 88,
    dcfUpside: 15.1,
    shariah: "Compliant",
    description: "Meta's family of apps (Facebook, Instagram, WhatsApp, Threads) reaches 3.2B daily users, making it the world's largest social ad platform. Reality Labs remains a long-term moonshot in spatial computing.",
    moat: "Network effects across 3.2B users, ad targeting data, WhatsApp business",
    risks: ["Ad revenue cyclicality", "Reality Labs cash burn ($15B/yr)", "Regulatory pressure in EU"],
    revenueHistory: [85965, 117929, 116609, 134902, 134902],
    ebitdaHistory: [33991, 46499, 37497, 58269, 58269],
    fcfHistory: [23632, 39116, 19005, 43014, 40998],
    years: [2020, 2021, 2022, 2023, 2024],
    revenueForcast: [160000, 183000, 208000, 236000, 266000],
    impliedPrice: 575,
    wacc: 9.2,
    tgr: 3.5,
    exitMultiple: 20,
    bullPrice: 700,
    baseprice: 575,
    bearPrice: 380,
  },
  {
    ticker: "TSLA",
    name: "Tesla Inc.",
    sector: "Consumer Discretionary",
    industry: "Auto Manufacturers",
    marketCap: 660000,
    price: 207.05,
    change: -3.41,
    pct: -1.62,
    pe: 62.1,
    evEbitda: 36.8,
    revenue: 97690,
    revenueGrowth: 0.9,
    grossMargin: 17.9,
    ebitdaMargin: 12.1,
    netMargin: 5.5,
    fcfMargin: 3.2,
    roe: 10.5,
    debtToEbitda: 1.4,
    analystRating: "Hold",
    avgPt: 185,
    opportunityScore: 44,
    dcfUpside: -10.6,
    shariah: "Compliant",
    description: "Tesla is the global EV leader with expanding energy storage, Autopilot/FSD software, and a growing services business. Facing margin compression from price cuts but Robotaxi and FSD monetization are potential re-rating catalysts.",
    moat: "Supercharger network, OTA software, FSD data advantage, brand",
    risks: ["EV price war from Chinese competitors", "Delivery growth stalling", "Elon distraction (X, SpaceX)", "Valuation disconnected from fundamentals"],
    revenueHistory: [31536, 53823, 81462, 96773, 97690],
    ebitdaHistory: [4021, 8779, 17667, 14014, 11843],
    fcfHistory: [2786, 4674, 7562, 4358, 3125],
    years: [2020, 2021, 2022, 2023, 2024],
    revenueForcast: [110000, 130000, 155000, 185000, 220000],
    impliedPrice: 185,
    wacc: 11.2,
    tgr: 3.5,
    exitMultiple: 28,
    bullPrice: 280,
    baseprice: 185,
    bearPrice: 95,
  },
  {
    ticker: "AVGO",
    name: "Broadcom Inc.",
    sector: "Technology",
    industry: "Semiconductors",
    marketCap: 680000,
    price: 156.44,
    change: 1.23,
    pct: 0.79,
    pe: 30.2,
    evEbitda: 19.8,
    revenue: 51574,
    revenueGrowth: 51.2,
    grossMargin: 63.4,
    ebitdaMargin: 51.8,
    netMargin: 22.3,
    fcfMargin: 41.2,
    roe: 21.8,
    debtToEbitda: 3.2,
    analystRating: "Overweight",
    avgPt: 190,
    opportunityScore: 79,
    dcfUpside: 21.5,
    shariah: "Compliant",
    description: "Broadcom is a leading semiconductor and infrastructure software company (post-VMware). Its networking ASICs are critical for AI cluster interconnects, and VMware integration is on track to significantly expand margins.",
    moat: "Custom AI ASIC design relationships with hyperscalers, VMware enterprise stickiness",
    risks: ["VMware integration execution risk", "High leverage post-acquisition", "Concentrated customer base"],
    revenueHistory: [23888, 27450, 33203, 35819, 51574],
    ebitdaHistory: [12240, 15107, 18618, 19965, 26723],
    fcfHistory: [12002, 13788, 16276, 17632, 21265],
    years: [2020, 2021, 2022, 2023, 2024],
    revenueForcast: [62000, 72000, 82000, 92000, 102000],
    impliedPrice: 190,
    wacc: 9.6,
    tgr: 3.2,
    exitMultiple: 20,
    bullPrice: 230,
    baseprice: 190,
    bearPrice: 130,
  },
  {
    ticker: "AMD",
    name: "Advanced Micro Devices",
    sector: "Technology",
    industry: "Semiconductors",
    marketCap: 245000,
    price: 157.82,
    change: 2.45,
    pct: 1.58,
    pe: 185.0,
    evEbitda: 44.2,
    revenue: 22680,
    revenueGrowth: 14.2,
    grossMargin: 52.6,
    ebitdaMargin: 14.2,
    netMargin: 0.5,
    fcfMargin: 5.8,
    roe: 0.5,
    debtToEbitda: 1.0,
    analystRating: "Overweight",
    avgPt: 200,
    opportunityScore: 77,
    dcfUpside: 26.7,
    shariah: "Compliant",
    description: "AMD competes with NVIDIA in AI GPUs (MI300X) and with Intel in CPUs (Ryzen, EPYC). EPYC server CPUs are taking share from Intel, and MI300X is gaining traction with cloud customers as an NVDA alternative.",
    moat: "EPYC server CPU momentum, competitive GPU roadmap, x86 compatibility",
    risks: ["NVDA's CUDA moat is hard to overcome", "Execution on MI400 roadmap", "Slower data center GPU ramp than expected"],
    revenueHistory: [9763, 16434, 23601, 22680, 22680],
    ebitdaHistory: [1641, 3643, 5613, 3213, 3213],
    fcfHistory: [771, 3270, 3565, 1316, 1316],
    years: [2020, 2021, 2022, 2023, 2024],
    revenueForcast: [30000, 40000, 52000, 65000, 78000],
    impliedPrice: 200,
    wacc: 10.8,
    tgr: 4.0,
    exitMultiple: 35,
    bullPrice: 275,
    baseprice: 200,
    bearPrice: 110,
  },
  {
    ticker: "JPM",
    name: "JPMorgan Chase & Co.",
    sector: "Financials",
    industry: "Money Center Banks",
    marketCap: 600000,
    price: 204.22,
    change: 1.13,
    pct: 0.56,
    pe: 12.4,
    evEbitda: null,
    revenue: 162000,
    revenueGrowth: 23.5,
    grossMargin: null,
    ebitdaMargin: null,
    netMargin: 27.8,
    fcfMargin: null,
    roe: 17.2,
    debtToEbitda: null,
    analystRating: "Overweight",
    avgPt: 225,
    opportunityScore: 70,
    dcfUpside: 10.2,
    shariah: "Non-Compliant",
    description: "JPMorgan is the world's largest bank by assets and a best-in-class franchise across investment banking, commercial banking, consumer, and asset management. CEO Jamie Dimon has built an unmatched fortress balance sheet.",
    moat: "Brand, scale, diversified revenue, fortress capital ratios",
    risks: ["Rate cut cycle compresses NII", "Capital requirements (Basel III endgame)", "Recession risk on credit losses"],
    revenueHistory: [119543, 121649, 128695, 162404, 162000],
    ebitdaHistory: [],
    fcfHistory: [],
    years: [2020, 2021, 2022, 2023, 2024],
    revenueForcast: [170000, 172000, 175000, 178000, 182000],
    impliedPrice: 225,
    wacc: 10.5,
    tgr: 2.5,
    exitMultiple: null,
    bullPrice: 265,
    baseprice: 225,
    bearPrice: 170,
  },
  {
    ticker: "LLY",
    name: "Eli Lilly and Company",
    sector: "Healthcare",
    industry: "Drug Manufacturers",
    marketCap: 750000,
    price: 788.11,
    change: 8.44,
    pct: 1.08,
    pe: 65.4,
    evEbitda: 45.8,
    revenue: 34124,
    revenueGrowth: 32.1,
    grossMargin: 79.2,
    ebitdaMargin: 31.4,
    netMargin: 22.5,
    fcfMargin: 18.0,
    roe: 76.4,
    debtToEbitda: 1.8,
    analystRating: "Overweight",
    avgPt: 950,
    opportunityScore: 85,
    dcfUpside: 20.5,
    shariah: "Compliant",
    description: "Eli Lilly is the largest pharmaceutical company by market cap, powered by Mounjaro/Zepbound (GLP-1 for diabetes/obesity) and Kisunla (Alzheimer's). The obesity drug market is estimated at $100B+ by 2030.",
    moat: "GLP-1 manufacturing scale advantage, strong pipeline, IP protection through 2030s",
    risks: ["Manufacturing capacity constraints limit revenue upside", "GLP-1 competition from Novo Nordisk, Roche, Amgen", "Drug pricing legislation (IRA)"],
    revenueHistory: [24540, 28318, 28541, 34124, 34124],
    ebitdaHistory: [7091, 8688, 7870, 10717, 10717],
    fcfHistory: [4971, 5703, 3971, 6143, 6143],
    years: [2020, 2021, 2022, 2023, 2024],
    revenueForcast: [48000, 62000, 75000, 88000, 100000],
    impliedPrice: 950,
    wacc: 8.5,
    tgr: 3.8,
    exitMultiple: 35,
    bullPrice: 1200,
    baseprice: 950,
    bearPrice: 650,
  },
  {
    ticker: "V",
    name: "Visa Inc.",
    sector: "Financials",
    industry: "Credit Services",
    marketCap: 545000,
    price: 268.81,
    change: 0.54,
    pct: 0.20,
    pe: 30.8,
    evEbitda: 26.2,
    revenue: 33255,
    revenueGrowth: 9.5,
    grossMargin: 80.8,
    ebitdaMargin: 67.8,
    netMargin: 54.2,
    fcfMargin: 57.8,
    roe: 45.2,
    debtToEbitda: 1.1,
    analystRating: "Overweight",
    avgPt: 310,
    opportunityScore: 73,
    dcfUpside: 15.3,
    shariah: "Non-Compliant",
    description: "Visa operates the world's largest electronic payments network. An asset-light toll-road on global commerce — each dollar spent on the network earns Visa a small but highly predictable fee. Exceptional FCF conversion and durable compounding.",
    moat: "Network effects, 4B cardholders, 130M merchant acceptance",
    risks: ["Central bank digital currencies (CBDC) disintermediation", "Antitrust scrutiny on interchange fees", "Buy Now Pay Later competition"],
    revenueHistory: [21846, 24105, 29310, 32654, 33255],
    ebitdaHistory: [14907, 16380, 19993, 22267, 22540],
    fcfHistory: [12022, 12474, 17919, 19712, 19228],
    years: [2020, 2021, 2022, 2023, 2024],
    revenueForcast: [36500, 40000, 43800, 47800, 52200],
    impliedPrice: 310,
    wacc: 8.8,
    tgr: 3.0,
    exitMultiple: 25,
    bullPrice: 370,
    baseprice: 310,
    bearPrice: 225,
  },
];

export const NEWS_FEED = [
  {
    id: 1,
    title: "NVIDIA's Blackwell GPU Platform Exceeds Supply Expectations, Analyst Raises Price Target to $1,200",
    summary: "Morgan Stanley upgrades NVDA citing faster-than-expected Blackwell ramp and sustained hyperscaler capex commitments. Data center revenue expected to exceed $100B in FY2025.",
    source: "Morgan Stanley Research",
    time: "2h ago",
    ticker: "NVDA",
    sentiment: "positive",
    catalystType: "Analyst Upgrade",
    catalystStrength: "High",
    financialImpact: "Revenue upside if Blackwell ramp sustains above consensus; estimate revisions likely.",
  },
  {
    id: 2,
    title: "Fed Officials Signal No Rate Cuts Until Core Inflation Drops Below 2.5%",
    summary: "Multiple Federal Reserve members reiterated a higher-for-longer stance, pushing back on market expectations for September cuts. 10-year Treasury yields rose 4bps on the news.",
    source: "Reuters",
    time: "4h ago",
    ticker: "MACRO",
    sentiment: "negative",
    catalystType: "Macro Event",
    catalystStrength: "High",
    financialImpact: "Increases discount rates across all equities; growth stocks most impacted. Financials may benefit from sustained NII.",
  },
  {
    id: 3,
    title: "Apple Intelligence Features Drive iPhone 16 Upgrade Cycle — Analysts Expect 10% YoY Unit Growth",
    summary: "Several analysts cite Apple Intelligence as a meaningful upgrade catalyst for the first time since the iPhone 12 super-cycle. ASP expansion expected alongside unit growth.",
    source: "Barclays Research",
    time: "6h ago",
    ticker: "AAPL",
    sentiment: "positive",
    catalystType: "Product Catalyst",
    catalystStrength: "Medium",
    financialImpact: "Potential +5–8% revenue beat in FY2025 iPhone segment; Services attach rate may also improve.",
  },
  {
    id: 4,
    title: "Eli Lilly Reports Mounjaro/Zepbound Revenues Up 185% YoY, Raises FY2024 Guidance",
    summary: "LLY smashed expectations with GLP-1 revenues of $3.08B vs $2.82B expected. Management raised full-year guidance by $2B at the midpoint citing unmet demand exceeding supply.",
    source: "Lilly Investor Relations",
    time: "8h ago",
    ticker: "LLY",
    sentiment: "positive",
    catalystType: "Earnings Beat",
    catalystStrength: "High",
    financialImpact: "Significant earnings and revenue estimate revisions likely across the street. Supply constraints remain the key bottleneck.",
  },
  {
    id: 5,
    title: "DOJ Files Antitrust Lawsuit Against Alphabet's Search Agreements",
    summary: "The DOJ is seeking remedies including forcing Google to divest Chrome browser and end default search agreements with Apple, Samsung, and Mozilla, which together generate ~$22B annually.",
    source: "Wall Street Journal",
    time: "1d ago",
    ticker: "GOOGL",
    sentiment: "negative",
    catalystType: "Regulatory Risk",
    catalystStrength: "High",
    financialImpact: "Could meaningfully impair Search revenue in a worst-case scenario. Market appears to be pricing in a partial remedy rather than full divestiture.",
  },
  {
    id: 6,
    title: "Amazon Web Services Revenue Accelerates to 17% Growth in Q1, Above 15% Consensus",
    summary: "AWS grew at the highest rate in 5 quarters, driven by enterprise AI workloads and Bedrock adoption. Amazon CEO Andy Jassy sees AI demand 'meaningfully exceeding supply.'",
    source: "Amazon Earnings Call",
    time: "2d ago",
    ticker: "AMZN",
    sentiment: "positive",
    catalystType: "Earnings Beat",
    catalystStrength: "High",
    financialImpact: "AWS segment margin expansion and growth acceleration are significant positives. AI tailwinds in cloud remain durable.",
  },
];

export const DISCOVERY_RESULTS = [
  {
    ticker: "CRWD",
    name: "CrowdStrike Holdings",
    sector: "Technology",
    opportunityScore: 88,
    marketCap: 78000,
    price: 332.14,
    revenueGrowth: 33.0,
    grossMargin: 77.4,
    analystRating: "Overweight",
    avgPt: 395,
    dcfUpside: 19.0,
    thesis: "CrowdStrike's Falcon platform is the fastest-growing cybersecurity platform. Net retention of 120%+ and expanding ARPU signal deep customer adoption.",
    catalysts: ["AI-native threat detection", "Platform consolidation tailwind", "FedRAMP expansion"],
    shariah: "Compliant",
  },
  {
    ticker: "ASML",
    name: "ASML Holding N.V.",
    sector: "Technology",
    opportunityScore: 85,
    marketCap: 390000,
    price: 988.02,
    revenueGrowth: 21.0,
    grossMargin: 51.2,
    analystRating: "Overweight",
    avgPt: 1150,
    dcfUpside: 16.4,
    thesis: "ASML is the sole supplier of EUV lithography machines, making it a monopoly in the most critical step of advanced chip manufacturing. Every TSMC, Samsung, and Intel advanced node requires ASML machines.",
    catalysts: ["High-NA EUV ramp (2024–2025)", "AI-driven semicap cycle upcycle", "No credible competitor"],
    shariah: "Compliant",
  },
  {
    ticker: "MELI",
    name: "MercadoLibre Inc.",
    sector: "Consumer Discretionary",
    opportunityScore: 82,
    marketCap: 85000,
    price: 1684.30,
    revenueGrowth: 35.6,
    grossMargin: 47.2,
    analystRating: "Overweight",
    avgPt: 2100,
    dcfUpside: 24.7,
    thesis: "MercadoLibre is the dominant e-commerce and fintech platform in Latin America. Mercado Pago is growing faster than the marketplace and has structural advantages in an underbanked market.",
    catalysts: ["Brazil e-commerce penetration still low", "Mercado Pago credit card expansion", "Logistics network advantage"],
    shariah: "Questionable",
  },
  {
    ticker: "ADBE",
    name: "Adobe Inc.",
    sector: "Technology",
    opportunityScore: 76,
    marketCap: 225000,
    price: 493.22,
    revenueGrowth: 10.8,
    grossMargin: 88.6,
    analystRating: "Overweight",
    avgPt: 600,
    dcfUpside: 21.7,
    thesis: "Adobe's Creative Cloud and Experience Cloud are deeply embedded in enterprise workflows. Firefly AI integration is driving model upgrades and new user acquisition without disrupting existing ARPU.",
    catalysts: ["Firefly monetization ramp", "Video AI expansion", "Acrobat AI features driving enterprise upsell"],
    shariah: "Compliant",
  },
  {
    ticker: "SPOT",
    name: "Spotify Technology",
    sector: "Communication Services",
    opportunityScore: 74,
    marketCap: 63000,
    price: 320.41,
    revenueGrowth: 20.2,
    grossMargin: 27.6,
    analystRating: "Overweight",
    avgPt: 380,
    dcfUpside: 18.6,
    thesis: "Spotify is transitioning from a music platform to a full audio entertainment network. Podcast monetization, audiobooks, and improving gross margins signal a multi-year profitability inflection.",
    catalysts: ["Gross margin expanding toward 30%+", "Creator monetization tools", "Premium plan price increases"],
    shariah: "Compliant",
  },
  {
    ticker: "CELH",
    name: "Celsius Holdings",
    sector: "Consumer Staples",
    opportunityScore: 71,
    marketCap: 8200,
    price: 36.88,
    revenueGrowth: 18.5,
    grossMargin: 49.8,
    analystRating: "Overweight",
    avgPt: 55,
    dcfUpside: 49.2,
    thesis: "Celsius has disrupted the energy drink market with a health-forward brand, growing from 4% to 12% US market share. The PepsiCo distribution partnership gives it a long-term structural advantage.",
    catalysts: ["International expansion (Europe, Asia)", "New product innovation", "PepsiCo shelf space rollout"],
    shariah: "Compliant",
  },
];

export const TOP_PLAYS = [
  {
    ticker: "NVDA",
    name: "NVIDIA Corporation",
    sector: "Technology",
    marketCap: 2980000,
    price: 120.44,
    analystRating: "Overweight",
    avgPt: 150,
    opportunityScore: 91,
    bullCase: { price: 145, thesis: "Blackwell demand exceeds supply; hyperscaler capex commitments expand to 2027." },
    baseCase: { price: 128, thesis: "Steady AI GPU demand; datacenter revenue meets consensus." },
    bearCase: { price: 98, thesis: "Export controls expand; hyperscaler capex pauses; valuation de-rating." },
    whyNow: "Blackwell revenue recognition begins this quarter. Demand backlog of 3-4 quarters. Analyst estimates likely too low.",
    upside: "Blackwell supercycle, $200B AI infrastructure spending in 2025",
    downside: "Concentration risk: 4 hyperscalers = 40% of revenue",
    shariah: "Compliant",
  },
  {
    ticker: "META",
    name: "Meta Platforms Inc.",
    sector: "Communication Services",
    marketCap: 1260000,
    price: 499.42,
    analystRating: "Overweight",
    avgPt: 575,
    opportunityScore: 88,
    bullCase: { price: 580, thesis: "Threads monetization launches; AI-driven ad efficiency continues; new advertiser categories emerge." },
    baseCase: { price: 530, thesis: "Ad revenue grows ~18%; margin expansion continues toward 45%." },
    bearCase: { price: 420, thesis: "FTC scrutiny intensifies; Reality Labs losses disappoint; ad market softens." },
    whyNow: "AI-driven ad relevance scores are the highest in company history. Cost discipline has structurally expanded margins.",
    upside: "AI ad optimization, Threads business model launch, WhatsApp Business",
    downside: "Reality Labs cash burn, regulatory risk in EU",
    shariah: "Compliant",
  },
  {
    ticker: "LLY",
    name: "Eli Lilly and Company",
    sector: "Healthcare",
    marketCap: 750000,
    price: 788.11,
    analystRating: "Overweight",
    avgPt: 950,
    opportunityScore: 85,
    bullCase: { price: 980, thesis: "Manufacturing capacity doubles by 2025; Zepbound obesity indication expands to NASH and heart failure; pipeline readouts positive." },
    baseCase: { price: 870, thesis: "GLP-1 supply constraint eases gradually; FY2025 revenue of ~$48B." },
    bearCase: { price: 650, thesis: "Manufacturing expansion delayed; competition from Novo intensifies on price; IRA drug pricing limits obesity drug reimbursement." },
    whyNow: "Strong earnings guidance raise signals supply constraints easing faster than expected. Multiple near-term pipeline readouts expected.",
    upside: "Obesity drug market $100B+ opportunity; NASH and cardiovascular expansion",
    downside: "Premium valuation requires consistent execution",
    shariah: "Compliant",
  },
];

export const FUTURE_GIANTS = [
  {
    ticker: "PLTR",
    name: "Palantir Technologies",
    sector: "Technology",
    marketCap: 52000,
    price: 23.84,
    revenueGrowth: 27.0,
    upside: "3–5x",
    timeframe: "5–7 years",
    opportunityScore: 79,
    thesis: "Palantir's AIP platform is converting AI interest into enterprise production deployments at unprecedented speed. The 'boot camp' model creates a visceral product experience that leads to rapid land-and-expand cycles.",
    moat: "Government relationships (classified contracts), AIP data flywheel, mission-critical integrations",
    tam: "$500B+ enterprise AI and analytics TAM",
    risks: ["Government budget cuts", "High valuation requires sustained hypergrowth", "Competition from Palantir-adjacent platforms"],
    keyMetrics: { nrr: "120%", usComRevGrowth: "55%", ruleOf40: "47" },
    shariah: "Compliant",
  },
  {
    ticker: "DUOL",
    name: "Duolingo Inc.",
    sector: "Technology",
    marketCap: 11000,
    price: 246.22,
    revenueGrowth: 45.0,
    upside: "3–5x",
    timeframe: "5–8 years",
    opportunityScore: 76,
    thesis: "Duolingo is becoming the world's language learning infrastructure. Super Duolingo (subscription) is accelerating, and AI-generated lessons reduce content costs while dramatically personalizing learning paths.",
    moat: "Daily Active User habits, gamification engagement loop, AI lesson personalization at scale",
    tam: "$60B global language learning market",
    risks: ["Limited monetization outside language learning", "Google or Apple launching competing product"],
    keyMetrics: { dau: "34.1M", subGrowth: "56%", revenuePerDau: "$14.6" },
    shariah: "Compliant",
  },
  {
    ticker: "AXON",
    name: "Axon Enterprise Inc.",
    sector: "Industrials",
    marketCap: 26000,
    price: 328.11,
    revenueGrowth: 33.0,
    upside: "2–4x",
    timeframe: "5–7 years",
    opportunityScore: 73,
    thesis: "Axon is the operating system for law enforcement: TASER, body cameras, evidence.com cloud, and AI-powered real-time crime center. The subscription flywheel drives increasing ARPU with high switching costs.",
    moat: "Government contract stickiness, evidence.com monopoly in police video storage",
    tam: "$50B+ public safety technology market",
    risks: ["Political/regulatory risk around policing technology", "International expansion slower than domestic", "Valuation premium"],
    keyMetrics: { nrr: "122%", arpu: "+18% YoY", cloudMix: "68%" },
    shariah: "Compliant",
  },
];

export const SHARIAH_UNIVERSE = [
  { ticker: "AAPL", name: "Apple Inc.", status: "Compliant", businessScore: "Pass", debtScore: "Pass", cashScore: "Pass", note: "Minimal interest income relative to revenue" },
  { ticker: "MSFT", name: "Microsoft", status: "Compliant", businessScore: "Pass", debtScore: "Pass", cashScore: "Pass", note: "Cloud and software — no prohibited activities" },
  { ticker: "NVDA", name: "NVIDIA", status: "Compliant", businessScore: "Pass", debtScore: "Pass", cashScore: "Pass", note: "Semiconductor company — no prohibited activities" },
  { ticker: "AMZN", name: "Amazon", status: "Questionable", businessScore: "Pass", debtScore: "Pass", cashScore: "Borderline", note: "Interest income from financial services near threshold" },
  { ticker: "GOOGL", name: "Alphabet", status: "Compliant", businessScore: "Pass", debtScore: "Pass", cashScore: "Pass", note: "Advertising/cloud — note minor insurance income" },
  { ticker: "META", name: "Meta Platforms", status: "Compliant", businessScore: "Pass", debtScore: "Pass", cashScore: "Pass", note: "Social media/advertising" },
  { ticker: "TSLA", name: "Tesla", status: "Compliant", businessScore: "Pass", debtScore: "Pass", cashScore: "Pass", note: "EV manufacturer — clean" },
  { ticker: "JPM", name: "JPMorgan Chase", status: "Non-Compliant", businessScore: "Fail", debtScore: "Fail", cashScore: "Fail", note: "Interest-based banking — prohibited" },
  { ticker: "V", name: "Visa Inc.", status: "Non-Compliant", businessScore: "Fail", debtScore: "Pass", cashScore: "Pass", note: "Core business involves interest-based payment network fees" },
  { ticker: "LLY", name: "Eli Lilly", status: "Compliant", businessScore: "Pass", debtScore: "Pass", cashScore: "Pass", note: "Pharmaceutical — permissible healthcare" },
  { ticker: "AVGO", name: "Broadcom", status: "Compliant", businessScore: "Pass", debtScore: "Borderline", cashScore: "Pass", note: "High debt post-VMware but interest/revenue ratio below threshold" },
  { ticker: "AMD", name: "AMD", status: "Compliant", businessScore: "Pass", debtScore: "Pass", cashScore: "Pass", note: "Semiconductor — no prohibited activities" },
];
